// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['NativeService']['DownloadFile'](arg1, arg2);
}

export function GetPlatform() {
  return window['go']['main']['NativeService']['GetPlatform']();
}

export function IsFocused() {
  return window['go']['main']['NativeService']['IsFocused']();
}

export function ProxyFetchManifest(arg1) {
  return window['go']['main']['NativeService']['ProxyFetchManifest'](arg1);
}

export function RelinquishFocus() {
  return window['go']['main']['NativeService']['RelinquishFocus']();
}

export function RequestFocus() {
  return window['go']['main']['NativeService']['RequestFocus']();
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['NativeService']['SaveFileDialog'](arg1, arg2);
}

export function SaveMnemonic(arg1) {
  return window['go']['main']['NativeService']['SaveMnemonic'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['NativeService']['SetContext'](arg1);
}
