// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function DownloadFile(arg1:string,arg2:Array<number>):Promise<main.FileResult>;

export function GetPlatform():Promise<string>;

export function IsFocused():Promise<boolean>;

export function ProxyFetchManifest(arg1:string):Promise<main.ManifestProxyResult>;

export function RelinquishFocus():Promise<void>;

export function RequestFocus():Promise<void>;

export function SaveFileDialog(arg1:string,arg2:Array<number>):Promise<main.FileResult>;

export function SaveMnemonic(arg1:string):Promise<main.FileResult>;

export function SetContext(arg1:context.Context):Promise<void>;
