// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallMethod(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function Cleanup():Promise<void>;

export function InitializeServices(arg1:string,arg2:string):Promise<void>;

export function IsAvailable(arg1:string,arg2:string):Promise<boolean>;

export function MakeAvailable(arg1:string,arg2:string):Promise<string>;
