// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallWalletMethod(arg1, arg2, arg3) {
  return window['go']['main']['WalletService']['CallWalletMethod'](arg1, arg2, arg3);
}

export function GetNetwork() {
  return window['go']['main']['WalletService']['GetNetwork']();
}

export function GetSettings() {
  return window['go']['main']['WalletService']['GetSettings']();
}

export function InitializeWallet(arg1, arg2) {
  return window['go']['main']['WalletService']['InitializeWallet'](arg1, arg2);
}

export function IsWalletReady() {
  return window['go']['main']['WalletService']['IsWalletReady']();
}

export function SetSettings(arg1) {
  return window['go']['main']['WalletService']['SetSettings'](arg1);
}

export function ShutdownWallet() {
  return window['go']['main']['WalletService']['ShutdownWallet']();
}
