// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppName() {
  return window['go']['main']['App']['GetAppName']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}
