// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppName():Promise<string>;

export function GetAppVersion():Promise<string>;

export function OpenExternalURL(arg1:string):Promise<void>;
