// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallMethod(arg1, arg2, arg3, arg4) {
  return window['go']['main']['StorageProxyService']['CallMethod'](arg1, arg2, arg3, arg4);
}

export function Cleanup() {
  return window['go']['main']['StorageProxyService']['Cleanup']();
}

export function InitializeServices(arg1, arg2) {
  return window['go']['main']['StorageProxyService']['InitializeServices'](arg1, arg2);
}

export function IsAvailable(arg1, arg2) {
  return window['go']['main']['StorageProxyService']['IsAvailable'](arg1, arg2);
}

export function MakeAvailable(arg1, arg2) {
  return window['go']['main']['StorageProxyService']['MakeAvailable'](arg1, arg2);
}
