// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallWalletMethod(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetNetwork():Promise<string>;

export function GetSettings():Promise<string>;

export function InitializeWallet(arg1:string,arg2:string):Promise<void>;

export function IsWalletReady():Promise<boolean>;

export function SetSettings(arg1:string):Promise<void>;

export function ShutdownWallet():Promise<void>;
